name: fetch-latest-megamillions

on:
  # push:
  #   branches:
  #     - main
  schedule:
    # Lottery schedule:
    #   ET:  Tuesday, Friday at 11:00 PM
    #   UTC: Wednesday, Saturday at 4:00 AM (EST - winter) or 3:00 AM (EDT - summer)
    # Cron schedule:
    #   ET:  Wednesday, Saturday at 1:00 AM, 7:00 AM (EST - winter) or 2:00 AM, 8:00 AM (EDT - summer)
    #   UTC: Wednesday, Saturday at 6:00 AM, 12:00 PM
    #
    # Run twice in case of failure to better ensure the newest number gets picked up
    # If it continues to fail re-run the historical data fetch and fix whatever the issue was
    - cron: "0 6,12 * * 3,6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install Python dependencies
        run: |-
          cd $GITHUB_WORKSPACE/scraper
          pip install -r requirements.txt

      # https://github.com/MarketingPipeline/Python-Selenium-Action/blob/main/.github/workflows/Selenium-Action_Template.yaml
      - name: Installed OS package list
        run: apt list --installed
      - name: Removing previous chrome instances on runner
        run: sudo apt purge google-chrome-stable
      - name: Installing OS packages
        run: pip install chromedriver-autoinstaller selenium

      - name: Fetch latest Mega Millions numbers
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |-
          cd $GITHUB_WORKSPACE/scraper
          python -m src.main megamillions
          cat $GITHUB_WORKSPACE/numbers/megamillions.csv
      - name: Commit megamillions.csv file if changed
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "JEFF-bot"
          git add -A
          git commit -m "Update megamillions data" || exit 0
          git push